artifacts_root: artifacts


# data ingestion configuration
data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Tiamz01/data_repo/raw/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion.zip
  unzip_dir: artifacts/data_ingestion

# data validation configuration
data_validation: 
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]

# data transformation configuration
data_transformation: 
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail



#model trainer
model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail


#model evaluation
model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evauation/metrics.csv